# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MeterReader_pb2 as MeterReader__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MeterReadingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddReading = channel.unary_unary(
        '/MeterReadingService/AddReading',
        request_serializer=MeterReader__pb2.ReadingPacket.SerializeToString,
        response_deserializer=MeterReader__pb2.StatusMessage.FromString,
        )
    self.Test = channel.unary_unary(
        '/MeterReadingService/Test',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class MeterReadingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddReading(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MeterReadingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddReading': grpc.unary_unary_rpc_method_handler(
          servicer.AddReading,
          request_deserializer=MeterReader__pb2.ReadingPacket.FromString,
          response_serializer=MeterReader__pb2.StatusMessage.SerializeToString,
      ),
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MeterReadingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
