version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4572-4581:4572-4581"
      - "8080:8080"
    environment:
      SERVICES: "sqs,sns,s3,cloudformation"
      LOCALSTACK_HOSTNAME: "localhost"
      PORT_WEB_UI: "8080"
      DEBUG: "true"
      DEFAULT_REGION: "eu-west-2"
    volumes:
      - ~/tmp/localstack:/tmp/localstack